services:
  - type: web
    name: taskflow-api
    env: node
    plan: free
    autoDeploy: true
    buildCommand: npm install --include=dev && npm run build
    startCommand: npx prisma db push && npm start
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        value: 6379
      - key: REDIS_PASSWORD
        sync: false
      - key: REDIS_URL
        sync: false
      - key: JWT_SECRET
        value: super-secret-access-token-key-taskflow-2026
      - key: JWT_REFRESH_SECRET
        value: super-secret-refresh-token-key-taskflow-2026
      - key: JWT_ACCESS_EXPIRES_IN
        value: 15m

  - type: worker
    name: taskflow-worker
    env: node
    plan: free
    autoDeploy: true
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run start:worker
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        value: 6379
      - key: REDIS_PASSWORD
        sync: false




